In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import timedelta
import glob

In [14]:
df = pd.read_csv('input/e_t_050924_tudo_conec_1_7_020130944393348.csv',
                skipinitialspace=True,
                # skiprows=range(10),
                # dtype = str,
                delimiter=';')

#df.columns = df.columns.str.replace(' ', '')

# for col in df.columns:
#     df[col].str.strip()

In [ ]:
# df.dtypes

In [15]:
df[['TU1', 'TU2', 'TU3']] = df['TU'].str.split('.', expand=True)
df

,TU,ELEV,AZIM,DIST,ERRO ELEV,ERRO AZIM,ERRO DIST,MODO ELEV,MODO AZIM,MODO DIST,...,BP AZIM,BP DIST,S/B REC,S/B TLM,MODO RECEP,VEL ELEV,VEL AZIM,TU1,TU2,TU3
0,13:09:44.398.473,23.42884,218.62046,1.097936e+06,-2.10368,1.14441,-22.21686,D,D,D,...,7,6,5.3855,0,RADAR,0.0,0.0,13:09:44,398,473
1,13:09:44.407.12,23.42884,218.62046,1.097936e+06,-2.63265,-0.21871,-5.12697,D,D,D,...,7,6,5.3855,1730,RADAR,0.0,0.0,13:09:44,407,12
2,13:09:44.415.551,23.42884,218.62046,1.097936e+06,0.14343,-1.61235,-29.29695,D,D,D,...,7,6,5.3855,5190,RADAR,0.0,0.0,13:09:44,415,551
3,13:09:44.424.90,23.42884,218.62046,1.097936e+06,0.31128,-0.21566,-26.36726,D,D,D,...,7,6,5.3855,0,RADAR,0.0,0.0,13:09:44,424,90
4,13:09:44.432.630,23.42884,218.62046,1.097936e+06,-0.94198,0.64189,10.74222,D,D,D,...,7,6,0.1880,0,RADAR,0.0,0.0,13:09:44,432,630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4592,13:10:26.320.473,32.26356,209.66300,8.805797e+05,0.01729,-0.14242,1.70899,D,D,D,...,7,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,320,473
4593,13:10:26.329.12,32.26597,209.66025,8.805320e+05,-0.65511,-1.09558,-6.10353,D,D,D,...,7,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,329,12
4594,13:10:26.337.550,32.26854,209.65785,8.804842e+05,0.34688,0.40995,18.06645,D,D,D,...,7,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,337,550
4595,13:10:26.346.89,32.27077,209.65562,8.804365e+05,-0.31738,-0.43844,-11.71878,D,D,D,...,7,6,0.0000,5190,RADAR,0.0,-0.0,13:10:26,346,89
4596,13:10:26.354.627,32.27266,209.65356,8.803887e+05,-0.54525,-1.81681,14.16019,D,D,D,...,7,6,0.0000,0,RADAR,0.0,-0.0,13:10:26,354,627

In [16]:

df["TU1d"]= pd.to_datetime("2024-06-09 " + df["TU1"], format="%Y-%m-%d %H:%M:%S") + pd.to_timedelta(df["TU2"].astype('int64'), unit='ms') + pd.to_timedelta(df["TU3"].astype('int64'), unit='us')
#df["TU1d"]= pd.to_datetime(df["TU1"], format="%H:%M:%S") + pd.to_timedelta(df["TU2"].astype('int64'), unit='ms') + pd.to_timedelta(df["TU3"].astype('int64'), unit='us')

df

,TU,ELEV,AZIM,DIST,ERRO ELEV,ERRO AZIM,ERRO DIST,MODO ELEV,MODO AZIM,MODO DIST,...,BP DIST,S/B REC,S/B TLM,MODO RECEP,VEL ELEV,VEL AZIM,TU1,TU2,TU3,TU1d
0,13:09:44.398.473,23.42884,218.62046,1.097936e+06,-2.10368,1.14441,-22.21686,D,D,D,...,6,5.3855,0,RADAR,0.0,0.0,13:09:44,398,473,2024-06-09 13:09:44.398473
1,13:09:44.407.12,23.42884,218.62046,1.097936e+06,-2.63265,-0.21871,-5.12697,D,D,D,...,6,5.3855,1730,RADAR,0.0,0.0,13:09:44,407,12,2024-06-09 13:09:44.407012
2,13:09:44.415.551,23.42884,218.62046,1.097936e+06,0.14343,-1.61235,-29.29695,D,D,D,...,6,5.3855,5190,RADAR,0.0,0.0,13:09:44,415,551,2024-06-09 13:09:44.415551
3,13:09:44.424.90,23.42884,218.62046,1.097936e+06,0.31128,-0.21566,-26.36726,D,D,D,...,6,5.3855,0,RADAR,0.0,0.0,13:09:44,424,90,2024-06-09 13:09:44.424090
4,13:09:44.432.630,23.42884,218.62046,1.097936e+06,-0.94198,0.64189,10.74222,D,D,D,...,6,0.1880,0,RADAR,0.0,0.0,13:09:44,432,630,2024-06-09 13:09:44.432630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4592,13:10:26.320.473,32.26356,209.66300,8.805797e+05,0.01729,-0.14242,1.70899,D,D,D,...,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,320,473,2024-06-09 13:10:26.320473
4593,13:10:26.329.12,32.26597,209.66025,8.805320e+05,-0.65511,-1.09558,-6.10353,D,D,D,...,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,329,12,2024-06-09 13:10:26.329012
4594,13:10:26.337.550,32.26854,209.65785,8.804842e+05,0.34688,0.40995,18.06645,D,D,D,...,6,0.0000,1730,RADAR,0.0,-0.0,13:10:26,337,550,2024-06-09 13:10:26.337550
4595,13:10:26.346.89,32.27077,209.65562,8.804365e+05,-0.31738,-0.43844,-11.71878,D,D,D,...,6,0.0000,5190,RADAR,0.0,-0.0,13:10:26,346,89,2024-06-09 13:10:26.346089
4596,13:10:26.354.627,32.27266,209.65356,8.803887e+05,-0.54525,-1.81681,14.16019,D,D,D,...,6,0.0000,0,RADAR,0.0,-0.0,13:10:26,354,627,2024-06-09 13:10:26.354627

In [17]:
df["TU1d_1"]=df["TU1d"].shift(1)
df["sample"]=df["TU1d"] - df["TU1d_1"]
df_filtrado = df[df['sample'] > timedelta( seconds=0.03) ]
df_filtrado

,TU,ELEV,AZIM,DIST,ERRO ELEV,ERRO AZIM,ERRO DIST,MODO ELEV,MODO AZIM,MODO DIST,...,S/B TLM,MODO RECEP,VEL ELEV,VEL AZIM,TU1,TU2,TU3,TU1d,TU1d_1,sample
2633,13:10:07.8.323,27.81170,214.50540,977462.79147,-1.31632,-0.14343,29.78523,D,D,D,...,0,RADAR,0.0,-0.0,13:10:07,8,323,2024-06-09 13:10:07.008323,2024-06-09 13:10:06.977594,0 days 00:00:00.030729
2699,13:10:08.108.261,28.04996,214.26713,971716.93531,0.78532,0.63477,15.62504,D,D,D,...,0,RADAR,0.0,-0.0,13:10:08,108,261,2024-06-09 13:10:08.108261,2024-06-09 13:10:08.075815,0 days 00:00:00.032446
2928,13:10:11.675.833,28.83222,213.46221,953294.10268,-1.49231,0.22583,-7.81252,D,D,D,...,7785,RADAR,0.0,-0.0,13:10:11,675,833,2024-06-09 13:10:11.675833,2024-06-09 13:10:11.641677,0 days 00:00:00.034156

In [18]:
df['sample_txt'] = df['sample'].astype('str')
df['sample_txt'] = df['sample_txt'].str.split(' ', expand=True)[2]
df['sample_txt'] = df['sample_txt'].str[7:]
df['sample_txt'] = df['sample_txt'].str.replace('.',',')
# df['sample_txt'] = df['sample_txt'].apply(lambda x:x.split(' ')[2])
#df.to_csv("teste.csv", date_format='%H:%M:%S,%f')
df

,TU,ELEV,AZIM,DIST,ERRO ELEV,ERRO AZIM,ERRO DIST,MODO ELEV,MODO AZIM,MODO DIST,...,MODO RECEP,VEL ELEV,VEL AZIM,TU1,TU2,TU3,TU1d,TU1d_1,sample,sample_txt
0,13:09:44.398.473,23.42884,218.62046,1.097936e+06,-2.10368,1.14441,-22.21686,D,D,D,...,RADAR,0.0,0.0,13:09:44,398,473,2024-06-09 13:09:44.398473,NaT,NaT,None
1,13:09:44.407.12,23.42884,218.62046,1.097936e+06,-2.63265,-0.21871,-5.12697,D,D,D,...,RADAR,0.0,0.0,13:09:44,407,12,2024-06-09 13:09:44.407012,2024-06-09 13:09:44.398473,0 days 00:00:00.008539,"0,008539"
2,13:09:44.415.551,23.42884,218.62046,1.097936e+06,0.14343,-1.61235,-29.29695,D,D,D,...,RADAR,0.0,0.0,13:09:44,415,551,2024-06-09 13:09:44.415551,2024-06-09 13:09:44.407012,0 days 00:00:00.008539,"0,008539"
3,13:09:44.424.90,23.42884,218.62046,1.097936e+06,0.31128,-0.21566,-26.36726,D,D,D,...,RADAR,0.0,0.0,13:09:44,424,90,2024-06-09 13:09:44.424090,2024-06-09 13:09:44.415551,0 days 00:00:00.008539,"0,008539"
4,13:09:44.432.630,23.42884,218.62046,1.097936e+06,-0.94198,0.64189,10.74222,D,D,D,...,RADAR,0.0,0.0,13:09:44,432,630,2024-06-09 13:09:44.432630,2024-06-09 13:09:44.424090,0 days 00:00:00.008540,"0,008540"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4592,13:10:26.320.473,32.26356,209.66300,8.805797e+05,0.01729,-0.14242,1.70899,D,D,D,...,RADAR,0.0,-0.0,13:10:26,320,473,2024-06-09 13:10:26.320473,2024-06-09 13:10:26.311933,0 days 00:00:00.008540,"0,008540"
4593,13:10:26.329.12,32.26597,209.66025,8.805320e+05,-0.65511,-1.09558,-6.10353,D,D,D,...,RADAR,0.0,-0.0,13:10:26,329,12,2024-06-09 13:10:26.329012,2024-06-09 13:10:26.320473,0 days 00:00:00.008539,"0,008539"
4594,13:10:26.337.550,32.26854,209.65785,8.804842e+05,0.34688,0.40995,18.06645,D,D,D,...,RADAR,0.0,-0.0,13:10:26,337,550,2024-06-09 13:10:26.337550,2024-06-09 13:10:26.329012,0 days 00:00:00.008538,"0,008538"
4595,13:10:26.346.89,32.27077,209.65562,8.804365e+05,-0.31738,-0.43844,-11.71878,D,D,D,...,RADAR,0.0,-0.0,13:10:26,346,89,2024-06-09 13:10:26.346089,2024-06-09 13:10:26.337550,0 days 00:00:00.008539,"0,008539"
4596,13:10:26.354.627,32.27266,209.65356,8.803887e+05,-0.54525,-1.81681,14.16019,D,D,D,...,RADAR,0.0,-0.0,13:10:26,354,627,2024-06-09 13:10:26.354627,2024-06-09 13:10:26.346089,0 days 00:00:00.008538,"0,008538"

In [19]:
df.to_csv("teste.csv",
          index=False,
          #date_format='%H:%M:%S,%f',
          decimal=',',
          sep=';'
          )

In [8]:
df.dtypes

TU                     object
ELEV                  float64
AZIM                  float64
DIST                  float64
ERROELEV              float64
ERROAZIM              float64
ERRODIST              float64
MODOELEV               object
MODOAZIM               object
MODODIST               object
BPELEV                  int64
BPAZIM                  int64
BPDIST                  int64
S/BREC                float64
S/BTLM                  int64
MODORECEP              object
VELELEV               float64
VELAZIM               float64
TU1                    object
TU2                    object
TU3                    object
TU1d           datetime64[ns]
TU1d_1         datetime64[ns]
sample        timedelta64[ns]
sample_txt             object
dtype: object

In [ ]:
# df[df['Sensor']=='TOPDEC-LIG']

In [ ]:
# df.iloc[541:7443,:]

In [ ]:
# df[df['Elev']>5.0]

In [ ]:
import sqlite3
import pandas as pd
# Create your connection.
cnx = sqlite3.connect('e_BEARN_BEARN_001131454161321.dat')
print( cnx)

df = pd.read_sql_query("SELECT * FROM data", cnx)
df